= How to Use *coapt*
:author: Tristan M. Chase
:toc:

== Overview

*coapt* is a collection of *apt*-related scripts arranged in a logical order.  It will:

. Create a snapshot of your currently installed packages and exit if the `-s` or `--snapshot` option is passed (in the directory `$HOME/.local/share/coapt/snapshots`)
. Autoremove unused packages if the `-a` or `--autoremove` option is passed
. Update packages
. Hold any packages you specify at their current version (in the directory `$HOME/.local/share/coapt/hold`)
. Upgrade packages
. Release any hold on packages
. Clean the package cache
. Ask you if would like to reboot the system, if necessary

This script is designed to minimize problems encountered during upgrades.

== Usage

....
Usage: coapt [ {-d|--debug} ] [ {-h|--help} | {-s|--snapshot} | {-a|--autoremove} | {-i|--ignore-hold} ]

Examples: coapt; coapt --debug; coapt --autoremove

Options:
	-a --autoremove		Autoremove unused packages
	-d --debug		Enable debug mode
	-h --help		Display this help message
	   --holds		Manage held packages (not implemented yet)
	-i --ignore-hold	Ignore holds on packages
	-s --snapshot		Create a snapshot of installed packages and exit
....

== Installing

Copy and paste this into your favo[u]rite terminal:

....
sh -c "$(curl -fsSL https://raw.githubusercontent.com/tristanchase/coapt/main/install.sh)"
....
